name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift run -- just build
    - name: Test
      run: swift run -- just test --enable-coverage --coverage-threshold=0.0
    - name: Upload Test Results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Swift Tests
        path: .build/test.xml
        reporter: java-junit
    - name: Produce the coverage report
        uses: insightsengineering/coverage-action@v2
        with:
          # Path to the Cobertura XML report.
          path: .build/cobertura.xml
          # Minimum total coverage, if you want to the
          # workflow to enforce it as a standard.
          # This has no effect if the `fail` arg is set to `false`.
          threshold: 0.0
          # Fail the workflow if the minimum code coverage
          # reuqirements are not satisfied.
          fail: true
          # Publish the rendered output as a PR comment
          publish: true
    - name: Lint
      run: swift run -- just lint
